之前executor中的代码都是同步的，没有异步的代码，如果我们使用setTimeout模拟异步代码，就会发现没有任何输出，下面让我们做个测试：
```js
const Promise = require('./promise')

const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('成功了')
  }, 1000)
})

promise.then(value => {
  console.log(value)
}, reason => {
  console.log(reason)
})
```

没有任何输出，这是什么原因呢？这是因为executor中的代码为异步代码，当我们调用then方法中传入的回调函数时，此时Promise的状态很有可能仍然是pending状态，而Promise.then方法中我们只考虑了fulfilled和rejected两种状态，所以出现了此问题

再考虑如果开发者使用Promise实例调用了多次then方法，就会出现多个成功回调和失败回调，那么我们就需要定义两个数组，分别用来保存这些回调函数
```js
const PENDING = 'PENDING'
const FULFILLED = 'FULFILLED'
const REJECTED = 'REJECTED'
class Promise {
  constructor (executor) {
    this.status = PENDING
    this.value = undefined
    this.reason = undefined

    this.onFulfilledCallbacks = []
    this.onRejectedCallbacks = []
    const resolve = value => {
      if (this.status === PENDING) {
        this.status = FULFILLED
        this.value = value
        this.onFulfilledCallbacks.forEach(fn => fn())
      }
    }
    const reject = reason => {
      if (this.status === PENDING) {
        this.status = REJECTED
        this.reason = reason
        this.onRejectedCallbacks.forEach(fn => fn())
      }
    }

    try {
      executor(resolve, reject)
    } catch (e) {
      reject(e)
    }
  }

  then (onFulfilled, onRejected) {
    if (this.status === FULFILLED) {
      onFulfilled(this.value)
    }
    if (this.status === REJECTED) {
      onRejected(this.reason)
    }
    if (this.status === PENDING) {
      this.onFulfilledCallbacks.push(() => onFulfilled(this.value))
      this.onRejectedCallbacks.push(() => onRejected(this.reason))
    }
  }
}

module.exports = Promise
```